### ISSUE TITLE
AttributeError: module 'hnswlib' has no attribute 'TanimotoIndex'

### ISSUE THREAD

**Issue by DataViz94** [keiserlab/rad#1]
Hello
i have been running the DUDEZ_example.ipynb file, and I got this error: 

AttributeError                            Traceback (most recent call last)
Cell In[7], line 1
----> 1 hnsw_layer_graphs = getGraphs(dudez_fps, ef_construction=EF_CONSTRUCTION, M=M)

     83 def getGraphs(data, ef_construction=400, M=16):
---> 84     p = hnswlib.TanimotoIndex(dim=data.shape[1])
     85 #    p = hnswlib.Index(dim=data.shape[1])
     86     p.init_index(max_elements=len(data), ef_construction=ef_construction, M=M)

AttributeError: module 'hnswlib' has no attribute 'TanimotoIndex'

It looks the installation went ok. Many thanks if you have suggestions

**Comment by bwhall61** [comment]
Hi @DataViz94 thanks for pointing this out! 

What OS/system you are running on? I've only tested this on Linux so far so that could be an issue.  

Have you previously installed `hnswlib` from a different source? My guess is that the unmodified `hnswlib` is being installed/found and not my modified version (hence TanimotoIndex not being defined). I couldn't get this exactly reproduced, but I've updated the repo to give the modified `hnswlib` a different package name - now `hnswlib_rad`. Hopefully this will fix any potential naming conflicts.

Please pull the updated repo and try a fresh install, and let me know if that works!

**Comment by bwhall61** [comment]
Ah I think this could be it - could you please run `pip list | grep "rad"` and ensure that you get an output. It should look something like:
```
(base) bwhall61:~/Documents/rad$ pip list | grep "rad"
rad                       0.1
```
If you aren't seeing the line that says `rad       0.1` and are seeing no output then there is an issue with the installation.

If this is the case, please try navigating to the main `rad` project directory that contains the `setup.py` file and ensure that you have run `pip install .` to compile and install the required functions and that this results in no errors. (Note that this will require the directory to be called hnswlib and not hnswlib_rad so you may have to change that back). I suspect that your imports are working solely based on the file tree structure, hence needing to rename the directory hnswlib -> hnswlib_rad to get the imports to work and that the package has not been completely installed.

Please try those steps and let me know if that helps!

**Comment by DataViz94** [comment]
Thanks this helped indeed! My install was wrong, so started again, and now RAD runs fine. I also installed on a more recent Mac Metal, much faster to generate the fingerprints etc...Now need to read again your nice preprint.
Best
Bruno

**Comment by bwhall61** [comment]
Thanks Bruno - I'm glad that you got it working! Let me know if you run into any more difficulties that I can help with
